### PR TITLE
050422 release

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixed multiple equiv class clash - this was due to errors from UO which I have reported to them, for now I have removed them in the merged import file (Not sure how long it will take UO to get to the changes, but it doesnt seem to affect the ontology itself so happy to leave the temp fix in till theres movement there)

### CODE REVIEW

**Comment by patrick-lloyd-ray** [comment]
Looks good to me. I have a few new import terms I need for making new terms, so adding them here.

**Comment by shawntanzk** [comment]
@patrick-lloyd-ray - just a heads up, to refresh imports after adding them to the .txt file you need to run `sh run.sh make imports/merged_import.owl` (assuming you have cd into src/ontology)

**Comment by patrick-lloyd-ray** [comment]
Reverted. I'm getting a 

`Killed
make: *** [Makefile:338: mirror-chebi] Error 137`

on that command

**Comment by shawntanzk** [comment]
I'm guessing its memory issues (often is the case with "killed) 
How much memory is allocated to your docker?

**Comment by shawntanzk** [comment]
I've just ran the import, and it ran through, so im guessing its memory issues. My docker is set to 30gb, but that's overkill, the run.sh is set to 16GB so do make sure your docker memory setting is at least that (unless your computer doesn't have that much memory, in which case, like with CL, you can just make a ticket and assign it to me). I will make another release with the terms you wanted imported and make a PR :)

**Comment by patrick-lloyd-ray** [comment]
Yep, had to put it up to 16GB to get it through but it made it! Thanks!

**Comment by shawntanzk** [comment]
perfect, could you implement the branch then - its a bit complicated on my end with a fork >.<

**Comment by shawntanzk** [comment]
think all is good - just a heads up if your users use the TMN.owl file, you need to make a release for the newly imported terms to appear in it

**Comment by patrick-lloyd-ray** [comment]
Now getting (trying to prepare a release):

`dosdp validate -i ../patterns/dosdp-patterns/ && touch tmp/pattern_schema_checks
/bin/sh: 1: dosdp: not found
make: *** [Makefile:505: tmp/pattern_schema_checks] Error 127`

Any ideas? Something to do with DOSDP validation, but haven't gotten this error before.

**Comment by shawntanzk** [comment]
ill look into it tmr, defs seen this before, its something with the new ODK version - will fix and make a PR :) sorry for the insane amount of fixes needed, a whole lot of new features in ODK = whole lot more new things that can be broken >.<

**Comment by patrick-lloyd-ray** [comment]
No problem at all! Thanks for the help on it! (all the new stuff looks great so far, just a bit of trouble-shooting).

**Pull request merged**
